export type Tour = "ATP" | "WTA";

export type TourPlayerPortrait = {
  src: string;
  sourceUrl: string;
  credit: string;
  license: string;
  objectPosition?: string;
};

export type TourPlayer = {
  id: string;
  name: string;
  nameZh: string;
  tour: Tour;
  rank: number;
  country: string;
  countryCode: string;
  brand: string;
  marketedFamily: string;
  marketedModel?: string;
  mapping: "型号级映射" | "系列级映射" | "基础型号等效" | "当前拍系参考";
  portrait: TourPlayerPortrait;
  playStyle: string;
  signature: string;
  traits: readonly [string, string, string];
  profileUrl: string;
  gearUrl: string;
  note: string;
};

export const tourRankAsOf = "2026-07-13";

export const tourSources = {
  ATP: "https://www.atptour.com/en/rankings/singles?rankRange=1-10",
  WTA: "https://www.wtatennis.com/rankings/singles?date=2026-07-13",
};

const tourPortraits: Record<string, TourPlayerPortrait> = {
  "jannik-sinner": {
    src: "/players/jannik-sinner.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Jannik_Sinner_2025_US_Open.jpg",
    credit: "The White House",
    license: "Public domain",
    objectPosition: "50% 34%",
  },
  "alexander-zverev": {
    src: "/players/alexander-zverev.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Alexander_Zverev.jpg",
    credit: "Rick Munroe",
    license: "CC BY-SA 4.0",
    objectPosition: "50% 28%",
  },
  "carlos-alcaraz": {
    src: "/players/carlos-alcaraz.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:25th_Laureus_World_Sports_Awards_-_Red_Carpet_-_Carlos_Alcaraz_-_240422_192324_(cropped).jpg",
    credit: "Barcex",
    license: "CC BY-SA 4.0",
    objectPosition: "50% 25%",
  },
  "felix-auger-aliassime": {
    src: "/players/felix-auger-aliassime.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:F%C3%A9lix_Auger-Aliassime_(2023_DC_Open)_01_(cropped).jpg",
    credit: "Hameltion",
    license: "CC BY-SA 4.0",
    objectPosition: "50% 24%",
  },
  "alex-de-minaur": {
    src: "/players/alex-de-minaur.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Alex_de_Minaur_2024.jpg",
    credit: "Barcex",
    license: "CC BY-SA 4.0",
    objectPosition: "50% 30%",
  },
  "ben-shelton": {
    src: "/players/ben-shelton.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Ben_Shelton,_media_conference,_Swiss_Indoors_Basel_2025_(cropped).jpg",
    credit: "Skyscraper2010",
    license: "CC BY-SA 4.0",
    objectPosition: "50% 27%",
  },
  "novak-djokovic": {
    src: "/players/novak-djokovic.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Novak_Djokovic_Paris_2024_Olympic_Games_(cropped).jpg",
    credit: "Andymiah",
    license: "CC BY-SA 4.0",
    objectPosition: "50% 22%",
  },
  "daniil-medvedev": {
    src: "/players/daniil-medvedev.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Danill_Medvedev_Miami_2019_(cropped).jpg",
    credit: "LacosteWiki",
    license: "CC BY-SA 4.0",
    objectPosition: "50% 29%",
  },
  "aryna-sabalenka": {
    src: "/players/aryna-sabalenka.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Aryna_Sabalenka_(2024_DC_Open)_06.jpg",
    credit: "Hameltion",
    license: "CC BY-SA 4.0",
    objectPosition: "50% 26%",
  },
  "elena-rybakina": {
    src: "/players/elena-rybakina.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Elena_Rybakina_(2025_DC_Open)_11_(cropped).jpg",
    credit: "Hameltion",
    license: "CC BY-SA 4.0",
    objectPosition: "50% 27%",
  },
  "jessica-pegula": {
    src: "/players/jessica-pegula.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Jessica_Pegula_(2025_DC_Open)_01_(cropped).jpg",
    credit: "Hameltion",
    license: "CC BY-SA 4.0",
    objectPosition: "50% 27%",
  },
  "coco-gauff": {
    src: "/players/coco-gauff.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Coco_Gauff_Miami_Open.jpg",
    credit: "Rick Munroe",
    license: "CC BY-SA 4.0",
    objectPosition: "50% 24%",
  },
  "mirra-andreeva": {
    src: "/players/mirra-andreeva.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Mirra_Andreeva_WMQ23_(cropped).jpg",
    credit: "si.robi",
    license: "CC BY-SA 2.0",
    objectPosition: "50% 25%",
  },
  "karolina-muchova": {
    src: "/players/karolina-muchova.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Karol%C3%ADna_Muchov%C3%A1_(2023_US_Open)_25_(cropped2).jpg",
    credit: "Hameltion",
    license: "CC BY-SA 4.0",
    objectPosition: "50% 25%",
  },
  "linda-noskova": {
    src: "/players/linda-noskova.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Linda_Noskov%C3%A1_(2023_US_Open)_01_(cropped2).jpg",
    credit: "Hameltion",
    license: "CC BY-SA 4.0",
    objectPosition: "50% 25%",
  },
  "iga-swiatek": {
    src: "/players/iga-swiatek.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Iga_Swiatek_2023_Cropped_%2B_Retouched.jpg",
    credit: "Hameltion",
    license: "CC BY-SA 4.0",
    objectPosition: "50% 26%",
  },
};

export const tourPlayers: TourPlayer[] = [
  {
    id: "jannik-sinner",
    name: "Jannik Sinner",
    nameZh: "扬尼克·辛纳",
    tour: "ATP",
    rank: 1,
    country: "意大利",
    countryCode: "ITA",
    brand: "HEAD",
    marketedFamily: "Speed 2026",
    mapping: "系列级映射",
    portrait: tourPortraits["jannik-sinner"],
    playStyle: "底线提速",
    signature: "紧凑引拍把双翼速度压进落点，接发后很快接管回合。",
    traits: ["双翼提速", "接发压迫", "硬地节奏"],
    profileUrl: "https://www.head.com/en_GB/athletes/tennis/atp/jannik-sinner",
    gearUrl: "https://www.head.com/en/sports/tennis/speed-racquets/",
    note: "官网将辛纳归入 Speed 2026 系列，未把其比赛拍等同某个零售子型号。",
  },
  {
    id: "alexander-zverev",
    name: "Alexander Zverev",
    nameZh: "亚历山大·兹维列夫",
    tour: "ATP",
    rank: 2,
    country: "德国",
    countryCode: "GER",
    brand: "HEAD",
    marketedFamily: "Gravity",
    marketedModel: "Gravity PRO",
    mapping: "型号级映射",
    portrait: tourPortraits["alexander-zverev"],
    playStyle: "深区控制",
    signature: "依靠一发与反拍的纵深质量，在底线建立稳定的重球优势。",
    traits: ["一发压制", "反拍直线", "深区相持"],
    profileUrl: "https://www.head.com/en_SE/athletes/tennis/atp/alexander-zverev",
    gearUrl: "https://www.head.com/en_GB/sports/tennis/gravity-racquets",
    note: "Gravity PRO 是官网推荐零售映射；比赛拍重量、平衡与零售规格未被证实相同。",
  },
  {
    id: "carlos-alcaraz",
    name: "Carlos Alcaraz",
    nameZh: "卡洛斯·阿尔卡拉斯",
    tour: "ATP",
    rank: 3,
    country: "西班牙",
    countryCode: "ESP",
    brand: "Babolat",
    marketedFamily: "Pure Aero Gen9",
    marketedModel: "Pure Aero 98 Gen9",
    mapping: "型号级映射",
    portrait: tourPortraits["carlos-alcaraz"],
    playStyle: "全场爆发",
    signature: "用正拍上旋打开角度，再以变线、放短和前场终结改变节奏。",
    traits: ["正拍上旋", "前场终结", "节奏变化"],
    profileUrl: "https://www.babolat.com/us/carlos-alcaraz-pro-player.html",
    gearUrl: "https://www.babolat.com/us/pure-aero-98-gen9-unstrung/101567.html",
    note: "Babolat 明示职业球员可能使用定制或不同型号，零售 305g、16×20 不是比赛拍实测值。",
  },
  {
    id: "felix-auger-aliassime",
    name: "Félix Auger-Aliassime",
    nameZh: "费利克斯·奥热-阿利亚西姆",
    tour: "ATP",
    rank: 4,
    country: "加拿大",
    countryCode: "CAN",
    brand: "Babolat",
    marketedFamily: "Pure Aero Gen9",
    marketedModel: "Pure Aero 98 Gen9",
    mapping: "型号级映射",
    portrait: tourPortraits["felix-auger-aliassime"],
    playStyle: "发球抢攻",
    signature: "以发球和正拍第一板缩短回合，在上升期主动抢占场地。",
    traits: ["发球得分", "正拍第一板", "主动上网"],
    profileUrl: "https://www.babolat.com/at/felix-auger-aliassime-pro-player.html",
    gearUrl: "https://www.babolat.com/us/pure-aero-98-gen9-unstrung/101567.html",
    note: "官网产品绑定到 Pure Aero 98 Gen9，但同页也提示职业用拍可能是定制或不同型号。",
  },
  {
    id: "alex-de-minaur",
    name: "Alex de Minaur",
    nameZh: "亚历克斯·德米纳尔",
    tour: "ATP",
    rank: 5,
    country: "澳大利亚",
    countryCode: "AUS",
    brand: "Wilson",
    marketedFamily: "Ultra V5",
    mapping: "系列级映射",
    portrait: tourPortraits["alex-de-minaur"],
    playStyle: "速度反击",
    signature: "用覆盖范围和早点击球持续施压，把防守迅速转换成直线反击。",
    traits: ["快速移动", "早点击球", "反击变线"],
    profileUrl: "https://www.wilson.com/en-us/blog/tennis/unveiling-wilson-ultra-swing-with-power",
    gearUrl: "https://www.wilson.com/en-us/tennis/ultra/",
    note: "Wilson 确认其进入 Ultra 家族，未把具体比赛拍可靠绑定到 Ultra 99 Pro、100 或 100L。",
  },
  {
    id: "ben-shelton",
    name: "Ben Shelton",
    nameZh: "本·谢尔顿",
    tour: "ATP",
    rank: 6,
    country: "美国",
    countryCode: "USA",
    brand: "Yonex",
    marketedFamily: "EZONE 第 8 代",
    marketedModel: "EZONE 98",
    mapping: "型号级映射",
    portrait: tourPortraits["ben-shelton"],
    playStyle: "左手重炮",
    signature: "左手发球制造高弹跳与外角，再用正拍力量快速完成进攻。",
    traits: ["左手发球", "正拍爆发", "大胆抢攻"],
    profileUrl: "https://us.yonex.com/pages/athlete/ben-shelton",
    gearUrl: "https://us.yonex.com/products/ezone-98",
    note: "Yonex 运动员页说明职业选手可能使用规格不同的定制球拍。",
  },
  {
    id: "novak-djokovic",
    name: "Novak Djokovic",
    nameZh: "诺瓦克·德约科维奇",
    tour: "ATP",
    rank: 7,
    country: "塞尔维亚",
    countryCode: "SRB",
    brand: "HEAD",
    marketedFamily: "Speed Legend 2025",
    mapping: "当前拍系参考",
    portrait: tourPortraits["novak-djokovic"],
    playStyle: "全场控制",
    signature: "接发、落点和防守反击组成完整体系，能在任何节奏下重建回合。",
    traits: ["顶级接发", "反拍控制", "防转攻"],
    profileUrl: "https://www.head.com/en_US/sports/tennis/speed-legend",
    gearUrl: "https://www.head.com/it_IT/product/speed-pro-legend-2025-232066",
    note: "官网公开为 Speed Legend 系列，展示零售款不代表其比赛拍型号或规格。",
  },
  {
    id: "daniil-medvedev",
    name: "Daniil Medvedev",
    nameZh: "丹尼尔·梅德韦杰夫",
    tour: "ATP",
    rank: 8,
    country: "俄罗斯",
    countryCode: "RUS",
    brand: "Tecnifibre",
    marketedFamily: "T-Fight 2025",
    marketedModel: "T-Fight 305S",
    mapping: "型号级映射",
    portrait: tourPortraits["daniil-medvedev"],
    playStyle: "深位反击",
    signature: "站位深、挥拍平，以长度和变线让对手难以持续向前压迫。",
    traits: ["深位接发", "平击变线", "反击韧性"],
    profileUrl: "https://www.tecnifibre.com/en/pages/daniil-medvedev",
    gearUrl: "https://www.tecnifibre.com/en/products/t-fight-305s",
    note: "官网将梅德韦杰夫与 305S 产品绑定，但没有证明比赛拍完全采用零售 305S 参数。",
  },
  {
    id: "aryna-sabalenka",
    name: "Aryna Sabalenka",
    nameZh: "阿丽娜·萨巴伦卡",
    tour: "WTA",
    rank: 1,
    country: "白俄罗斯",
    countryCode: "BLR",
    brand: "Wilson",
    marketedFamily: "Blade V10",
    marketedModel: "Blade 98 18×20 V10",
    mapping: "型号级映射",
    portrait: tourPortraits["aryna-sabalenka"],
    playStyle: "强力进攻",
    signature: "发球和双翼力量直接穿透球场，短球出现时果断完成终结。",
    traits: ["发球重炮", "双翼穿透", "抢先终结"],
    profileUrl: "https://www.wilson.com/en-gb/blog/tennis/unveiling-wilson-blade-v10",
    gearUrl: "https://www.wilson.com/en-gb/tennis/blade/",
    note: "官网零售映射不等于比赛拍实测，零售重量、平衡等参数不能直接套用。",
  },
  {
    id: "elena-rybakina",
    name: "Elena Rybakina",
    nameZh: "伊莲娜·莱巴金娜",
    tour: "WTA",
    rank: 2,
    country: "哈萨克斯坦",
    countryCode: "KAZ",
    brand: "Yonex",
    marketedFamily: "VCORE 2026",
    marketedModel: "VCORE 100",
    mapping: "型号级映射",
    portrait: tourPortraits["elena-rybakina"],
    playStyle: "平击抢攻",
    signature: "流畅发球配合简洁平击，在较少多余动作下持续输出穿透力。",
    traits: ["发球效率", "平击穿透", "节奏简洁"],
    profileUrl: "https://us.yonex.com/pages/athlete/elena-rybakina",
    gearUrl: "https://us.yonex.com/pages/vcore",
    note: "Yonex 提醒职业球员可能使用规格不同的定制拍。",
  },
  {
    id: "jessica-pegula",
    name: "Jessica Pegula",
    nameZh: "杰西卡·佩古拉",
    tour: "WTA",
    rank: 3,
    country: "美国",
    countryCode: "USA",
    brand: "Yonex",
    marketedFamily: "EZONE 第 8 代",
    marketedModel: "EZONE 98",
    mapping: "型号级映射",
    portrait: tourPortraits["jessica-pegula"],
    playStyle: "早点击球",
    signature: "贴近底线借力回击，以双反和快速衔接持续压缩对手时间。",
    traits: ["借力回击", "双反提速", "底线站位"],
    profileUrl: "https://us.yonex.com/pages/athlete/jessica-pegula",
    gearUrl: "https://us.yonex.com/pages/ezone",
    note: "官网公开型号用于零售映射；职业定制规格可能不同。",
  },
  {
    id: "coco-gauff",
    name: "Coco Gauff",
    nameZh: "可可·高芙",
    tour: "WTA",
    rank: 4,
    country: "美国",
    countryCode: "USA",
    brand: "HEAD",
    marketedFamily: "Boom 2026",
    marketedModel: "Boom MP Alternate 2026",
    mapping: "基础型号等效",
    portrait: tourPortraits["coco-gauff"],
    playStyle: "防守转攻",
    signature: "移动与反拍构成稳固防线，再依靠发球和正拍寻找主动窗口。",
    traits: ["覆盖防守", "反拍稳定", "上旋正拍"],
    profileUrl: "https://www.head.com/en/athletes/tennis/wta/coco-gauff",
    gearUrl: "https://www.head.com/en/product/boom-mp-alternate-2026-232406",
    note: "MP Alternate 是官网主推的同款涂装/零售款；HEAD 明示展示型号可能不同于职业比赛拍。",
  },
  {
    id: "mirra-andreeva",
    name: "Mirra Andreeva",
    nameZh: "米拉·安德烈耶娃",
    tour: "WTA",
    rank: 5,
    country: "俄罗斯",
    countryCode: "RUS",
    brand: "Wilson",
    marketedFamily: "Blade V10",
    mapping: "系列级映射",
    portrait: tourPortraits["mirra-andreeva"],
    playStyle: "变化构建",
    signature: "用落点、旋转与节奏变化组织回合，在年轻打法中保留成熟判断。",
    traits: ["落点变化", "反拍稳定", "战术耐心"],
    profileUrl: "https://www.wilson.com/en-gb/blog/tennis/unveiling-wilson-blade-v10",
    gearUrl: "https://www.wilson.com/en-gb/tennis/blade/",
    note: "官方未可靠公开其具体子型号，因此只展示 Blade V10 家族。",
  },
  {
    id: "karolina-muchova",
    name: "Karolína Muchová",
    nameZh: "卡罗琳娜·穆霍娃",
    tour: "WTA",
    rank: 6,
    country: "捷克",
    countryCode: "CZE",
    brand: "HEAD",
    marketedFamily: "Speed 2026",
    mapping: "系列级映射",
    portrait: tourPortraits["karolina-muchova"],
    playStyle: "全场变化",
    signature: "切削、上网和直线突击不断切换，让对手难以锁定同一节奏。",
    traits: ["切削变化", "前场技术", "直线突击"],
    profileUrl: "https://www.head.com/en_US/athletes/tennis/wta/karolina-muchova",
    gearUrl: "https://www.head.com/en/sports/tennis/speed-racquets/",
    note: "HEAD 当前运动员映射为 Speed 系列，未把页面主图 Speed MP 等同其比赛拍。",
  },
  {
    id: "linda-noskova",
    name: "Linda Nosková",
    nameZh: "琳达·诺斯科娃",
    tour: "WTA",
    rank: 7,
    country: "捷克",
    countryCode: "CZE",
    brand: "Yonex",
    marketedFamily: "EZONE 第 8 代",
    marketedModel: "EZONE 98",
    mapping: "型号级映射",
    portrait: tourPortraits["linda-noskova"],
    playStyle: "主动平击",
    signature: "用发球和紧凑平击主动拿走时间，擅长在中前场完成提速。",
    traits: ["发球启动", "紧凑平击", "中场提速"],
    profileUrl: "https://us.yonex.com/pages/athlete/linda-noskova",
    gearUrl: "https://us.yonex.com/products/ezone-98",
    note: "Yonex 明示职业球员可能使用不同规格的定制拍。",
  },
  {
    id: "iga-swiatek",
    name: "Iga Świątek",
    nameZh: "伊加·斯瓦泰克",
    tour: "WTA",
    rank: 8,
    country: "波兰",
    countryCode: "POL",
    brand: "Tecnifibre",
    marketedFamily: "T-Fight 2025",
    marketedModel: "T-Fight 300S IG",
    mapping: "基础型号等效",
    portrait: tourPortraits["iga-swiatek"],
    playStyle: "上旋压迫",
    signature: "高强度移动配合重上旋正拍，把对手持续推离舒适击球区。",
    traits: ["重上旋", "接发压迫", "移动强度"],
    profileUrl: "https://www.tecnifibre.com/en/pages/iga-swiatek",
    gearUrl: "https://www.tecnifibre.com/en-ue/collections/raquettes-t-fight/products/tfight-300s-ig",
    note: "官网只明确这款涂装对应欧洲红土赛季至法网；温网后是否沿用及比赛拍参数均未证实。",
  },
];
