export type Tour = "ATP" | "WTA";

export type TourPlayer = {
  id: string;
  name: string;
  nameZh: string;
  tour: Tour;
  rank: number;
  country: string;
  countryCode: string;
  brand: string;
  marketedFamily: string;
  marketedModel?: string;
  mapping: "型号级映射" | "系列级映射" | "基础型号等效" | "当前拍系参考";
  racketImageId?: string;
  profileUrl: string;
  gearUrl: string;
  note: string;
};

export const tourRankAsOf = "2026-07-13";

export const tourSources = {
  ATP: "https://www.atptour.com/en/rankings/singles?rankRange=1-10",
  WTA: "https://www.wtatennis.com/rankings/singles?date=2026-07-13",
};

export const tourPlayers: TourPlayer[] = [
  {
    id: "jannik-sinner",
    name: "Jannik Sinner",
    nameZh: "扬尼克·辛纳",
    tour: "ATP",
    rank: 1,
    country: "意大利",
    countryCode: "ITA",
    brand: "HEAD",
    marketedFamily: "Speed 2026",
    mapping: "系列级映射",
    racketImageId: "head-speed-mp-2026",
    profileUrl: "https://www.head.com/en_GB/athletes/tennis/atp/jannik-sinner",
    gearUrl: "https://www.head.com/en/sports/tennis/speed-racquets/",
    note: "官网将辛纳归入 Speed 2026 系列，未把其比赛拍等同某个零售子型号。",
  },
  {
    id: "alexander-zverev",
    name: "Alexander Zverev",
    nameZh: "亚历山大·兹维列夫",
    tour: "ATP",
    rank: 2,
    country: "德国",
    countryCode: "GER",
    brand: "HEAD",
    marketedFamily: "Gravity",
    marketedModel: "Gravity PRO",
    mapping: "型号级映射",
    racketImageId: "head-gravity-mp-2025",
    profileUrl: "https://www.head.com/en_SE/athletes/tennis/atp/alexander-zverev",
    gearUrl: "https://www.head.com/en_GB/sports/tennis/gravity-racquets",
    note: "Gravity PRO 是官网推荐零售映射；比赛拍重量、平衡与零售规格未被证实相同。",
  },
  {
    id: "carlos-alcaraz",
    name: "Carlos Alcaraz",
    nameZh: "卡洛斯·阿尔卡拉斯",
    tour: "ATP",
    rank: 3,
    country: "西班牙",
    countryCode: "ESP",
    brand: "Babolat",
    marketedFamily: "Pure Aero Gen9",
    marketedModel: "Pure Aero 98 Gen9",
    mapping: "型号级映射",
    racketImageId: "babolat-pure-aero-98",
    profileUrl: "https://www.babolat.com/us/carlos-alcaraz-pro-player.html",
    gearUrl: "https://www.babolat.com/us/pure-aero-98-gen9-unstrung/101567.html",
    note: "Babolat 明示职业球员可能使用定制或不同型号，零售 305g、16×20 不是比赛拍实测值。",
  },
  {
    id: "felix-auger-aliassime",
    name: "Félix Auger-Aliassime",
    nameZh: "费利克斯·奥热-阿利亚西姆",
    tour: "ATP",
    rank: 4,
    country: "加拿大",
    countryCode: "CAN",
    brand: "Babolat",
    marketedFamily: "Pure Aero Gen9",
    marketedModel: "Pure Aero 98 Gen9",
    mapping: "型号级映射",
    racketImageId: "babolat-pure-aero-98",
    profileUrl: "https://www.babolat.com/at/felix-auger-aliassime-pro-player.html",
    gearUrl: "https://www.babolat.com/us/pure-aero-98-gen9-unstrung/101567.html",
    note: "官网产品绑定到 Pure Aero 98 Gen9，但同页也提示职业用拍可能是定制或不同型号。",
  },
  {
    id: "alex-de-minaur",
    name: "Alex de Minaur",
    nameZh: "亚历克斯·德米纳尔",
    tour: "ATP",
    rank: 5,
    country: "澳大利亚",
    countryCode: "AUS",
    brand: "Wilson",
    marketedFamily: "Ultra V5",
    mapping: "系列级映射",
    profileUrl: "https://www.wilson.com/en-us/blog/tennis/unveiling-wilson-ultra-swing-with-power",
    gearUrl: "https://www.wilson.com/en-us/tennis/ultra/",
    note: "Wilson 确认其进入 Ultra 家族，未把具体比赛拍可靠绑定到 Ultra 99 Pro、100 或 100L。",
  },
  {
    id: "ben-shelton",
    name: "Ben Shelton",
    nameZh: "本·谢尔顿",
    tour: "ATP",
    rank: 6,
    country: "美国",
    countryCode: "USA",
    brand: "Yonex",
    marketedFamily: "EZONE 第 8 代",
    marketedModel: "EZONE 98",
    mapping: "型号级映射",
    racketImageId: "yonex-ezone-98",
    profileUrl: "https://us.yonex.com/pages/athlete/ben-shelton",
    gearUrl: "https://us.yonex.com/products/ezone-98",
    note: "Yonex 运动员页说明职业选手可能使用规格不同的定制球拍。",
  },
  {
    id: "novak-djokovic",
    name: "Novak Djokovic",
    nameZh: "诺瓦克·德约科维奇",
    tour: "ATP",
    rank: 7,
    country: "塞尔维亚",
    countryCode: "SRB",
    brand: "HEAD",
    marketedFamily: "Speed Legend 2025",
    mapping: "当前拍系参考",
    racketImageId: "head-speed-mp-2026",
    profileUrl: "https://www.head.com/en_US/sports/tennis/speed-legend",
    gearUrl: "https://www.head.com/it_IT/product/speed-pro-legend-2025-232066",
    note: "官网公开为 Speed Legend 系列，展示零售款不代表其比赛拍型号或规格。",
  },
  {
    id: "daniil-medvedev",
    name: "Daniil Medvedev",
    nameZh: "丹尼尔·梅德韦杰夫",
    tour: "ATP",
    rank: 8,
    country: "俄罗斯",
    countryCode: "RUS",
    brand: "Tecnifibre",
    marketedFamily: "T-Fight 2025",
    marketedModel: "T-Fight 305S",
    mapping: "型号级映射",
    racketImageId: "tecnifibre-tfight-305s",
    profileUrl: "https://www.tecnifibre.com/en/pages/daniil-medvedev",
    gearUrl: "https://www.tecnifibre.com/en/products/t-fight-305s",
    note: "官网将梅德韦杰夫与 305S 产品绑定，但没有证明比赛拍完全采用零售 305S 参数。",
  },
  {
    id: "aryna-sabalenka",
    name: "Aryna Sabalenka",
    nameZh: "阿丽娜·萨巴伦卡",
    tour: "WTA",
    rank: 1,
    country: "白俄罗斯",
    countryCode: "BLR",
    brand: "Wilson",
    marketedFamily: "Blade V10",
    marketedModel: "Blade 98 18×20 V10",
    mapping: "型号级映射",
    racketImageId: "wilson-blade-98-v9",
    profileUrl: "https://www.wilson.com/en-gb/blog/tennis/unveiling-wilson-blade-v10",
    gearUrl: "https://www.wilson.com/en-gb/tennis/blade/",
    note: "官网零售映射不等于比赛拍实测，零售重量、平衡等参数不能直接套用。",
  },
  {
    id: "elena-rybakina",
    name: "Elena Rybakina",
    nameZh: "伊莲娜·莱巴金娜",
    tour: "WTA",
    rank: 2,
    country: "哈萨克斯坦",
    countryCode: "KAZ",
    brand: "Yonex",
    marketedFamily: "VCORE 2026",
    marketedModel: "VCORE 100",
    mapping: "型号级映射",
    racketImageId: "yonex-vcore-98",
    profileUrl: "https://us.yonex.com/pages/athlete/elena-rybakina",
    gearUrl: "https://us.yonex.com/pages/vcore",
    note: "Yonex 提醒职业球员可能使用规格不同的定制拍。",
  },
  {
    id: "jessica-pegula",
    name: "Jessica Pegula",
    nameZh: "杰西卡·佩古拉",
    tour: "WTA",
    rank: 3,
    country: "美国",
    countryCode: "USA",
    brand: "Yonex",
    marketedFamily: "EZONE 第 8 代",
    marketedModel: "EZONE 98",
    mapping: "型号级映射",
    racketImageId: "yonex-ezone-98",
    profileUrl: "https://us.yonex.com/pages/athlete/jessica-pegula",
    gearUrl: "https://us.yonex.com/pages/ezone",
    note: "官网公开型号用于零售映射；职业定制规格可能不同。",
  },
  {
    id: "coco-gauff",
    name: "Coco Gauff",
    nameZh: "可可·高芙",
    tour: "WTA",
    rank: 4,
    country: "美国",
    countryCode: "USA",
    brand: "HEAD",
    marketedFamily: "Boom 2026",
    marketedModel: "Boom MP Alternate 2026",
    mapping: "基础型号等效",
    racketImageId: "head-boom-mp-2024",
    profileUrl: "https://www.head.com/en/athletes/tennis/wta/coco-gauff",
    gearUrl: "https://www.head.com/en/product/boom-mp-alternate-2026-232406",
    note: "MP Alternate 是官网主推的同款涂装/零售款；HEAD 明示展示型号可能不同于职业比赛拍。",
  },
  {
    id: "mirra-andreeva",
    name: "Mirra Andreeva",
    nameZh: "米拉·安德烈耶娃",
    tour: "WTA",
    rank: 5,
    country: "俄罗斯",
    countryCode: "RUS",
    brand: "Wilson",
    marketedFamily: "Blade V10",
    mapping: "系列级映射",
    racketImageId: "wilson-blade-98-v9",
    profileUrl: "https://www.wilson.com/en-gb/blog/tennis/unveiling-wilson-blade-v10",
    gearUrl: "https://www.wilson.com/en-gb/tennis/blade/",
    note: "官方未可靠公开其具体子型号，因此只展示 Blade V10 家族。",
  },
  {
    id: "karolina-muchova",
    name: "Karolína Muchová",
    nameZh: "卡罗琳娜·穆霍娃",
    tour: "WTA",
    rank: 6,
    country: "捷克",
    countryCode: "CZE",
    brand: "HEAD",
    marketedFamily: "Speed 2026",
    mapping: "系列级映射",
    racketImageId: "head-speed-mp-2026",
    profileUrl: "https://www.head.com/en_US/athletes/tennis/wta/karolina-muchova",
    gearUrl: "https://www.head.com/en/sports/tennis/speed-racquets/",
    note: "HEAD 当前运动员映射为 Speed 系列，未把页面主图 Speed MP 等同其比赛拍。",
  },
  {
    id: "linda-noskova",
    name: "Linda Nosková",
    nameZh: "琳达·诺斯科娃",
    tour: "WTA",
    rank: 7,
    country: "捷克",
    countryCode: "CZE",
    brand: "Yonex",
    marketedFamily: "EZONE 第 8 代",
    marketedModel: "EZONE 98",
    mapping: "型号级映射",
    racketImageId: "yonex-ezone-98",
    profileUrl: "https://us.yonex.com/pages/athlete/linda-noskova",
    gearUrl: "https://us.yonex.com/products/ezone-98",
    note: "Yonex 明示职业球员可能使用不同规格的定制拍。",
  },
  {
    id: "iga-swiatek",
    name: "Iga Świątek",
    nameZh: "伊加·斯瓦泰克",
    tour: "WTA",
    rank: 8,
    country: "波兰",
    countryCode: "POL",
    brand: "Tecnifibre",
    marketedFamily: "T-Fight 2025",
    marketedModel: "T-Fight 300S IG",
    mapping: "基础型号等效",
    racketImageId: "tecnifibre-tfight-305s",
    profileUrl: "https://www.tecnifibre.com/en/pages/iga-swiatek",
    gearUrl: "https://www.tecnifibre.com/en-ue/collections/raquettes-t-fight/products/tfight-300s-ig",
    note: "官网只明确这款涂装对应欧洲红土赛季至法网；温网后是否沿用及比赛拍参数均未证实。",
  },
];
